enum AppErrorCode {
  locationTimeout,
  locationUnavailable,
  locationPermissionDenied,
  network,
  timeout,
  authEmailAlreadyExists,
  authWrongPassword,
  authInvalidCredentials,
  authSessionExpired,
  server,
  notFound,
  validation,
  unknown,
}
