# -*- coding: utf-8 -*-
# Run: python tools/gen_arb.py

strings = {
    "loginWelcome": ("Bienvenido 👋", "Welcome 👋"),
    "loginSubtitle": ("Inicia sesión en VetNow", "Sign in to VetNow"),
    "email": ("Email", "Email"),
    "password": ("Contraseña", "Password"),
    "loginErrorInvalidCredentials": (
        "Email o contraseña incorrectos",
        "Incorrect email or password",
    ),
    "signIn": ("Iniciar sesión", "Sign in"),
    "loginNoAccountRegister": (
        "¿No tienes cuenta? Regístrate",
        "Don't have an account? Sign up",
    ),
    "createAccount": ("Crear cuenta", "Create account"),
    "registerClinicTitle": ("Registro de clínica", "Clinic registration"),
    "registerOwnerTitle": ("Registro de propietario", "Owner registration"),
    "fullName": ("Nombre completo", "Full name"),
    "fillAllFields": ("Rellena todos los campos", "Fill in all fields"),
    "registerMustAcceptLegal": (
        "Debes aceptar la política de privacidad y los términos",
        "You must accept the privacy policy and terms",
    ),
    "registerError": (
        "Error al registrarse: {error}",
        "Registration error: {error}",
    ),
    "privacyPolicyLink": ("Política de Privacidad", "Privacy Policy"),
    "termsAndConditionsLink": ("Términos y Condiciones", "Terms and Conditions"),
    "consentPrefix": ("He leído y acepto la ", "I have read and accept the "),
    "roleSelectorTitle": ("¿Cómo usarás VetNow?", "How will you use VetNow?"),
    "selectYourProfile": ("Selecciona tu perfil", "Select your profile"),
    "roleOwnerTitle": ("Soy propietario", "I'm a pet owner"),
    "roleOwnerSubtitle": (
        "Busco clínicas y reservo citas para mi mascota",
        "I look for clinics and book appointments for my pet",
    ),
    "roleClinicTitle": ("Soy clínica", "I'm a clinic"),
    "roleClinicSubtitle": (
        "Gestiono mi agenda y recibo reservas",
        "I manage my schedule and receive bookings",
    ),
    "settingsTitle": ("Ajustes", "Settings"),
    "account": ("Cuenta", "Account"),
    "termsAndConditions": ("Términos y condiciones", "Terms and conditions"),
    "personalization": ("Personalización", "Personalization"),
    "privacyAndPolicy": ("Política y privacidad", "Privacy policy"),
    "deleteMyAccount": ("Eliminar mi cuenta", "Delete my account"),
    "signOut": ("Cerrar sesión", "Sign out"),
    "cancel": ("Cancelar", "Cancel"),
    "signOutConfirmMessage": (
        "¿Seguro que quieres cerrar sesión?",
        "Are you sure you want to sign out?",
    ),
    "signOutError": (
        "Error al cerrar sesión: {error}",
        "Error signing out: {error}",
    ),
    "deleteAccountConfirmBody": (
        "Esta acción eliminará tus datos personales y cerrará tu sesión. "
        "No se puede deshacer.\n\n¿Deseas continuar?",
        "This will delete your personal data and sign you out. "
        "It cannot be undone.\n\nDo you want to continue?",
    ),
    "deleteAccount": ("Eliminar cuenta", "Delete account"),
    "deleteAccountError": (
        "No se pudo eliminar la cuenta: {error}",
        "Could not delete account: {error}",
    ),
    "appVersionLabel": ("App version: 5.271.0", "App version: 5.271.0"),
    "darkMode": ("Modo oscuro", "Dark mode"),
    "enabled": ("Activado", "On"),
    "disabled": ("Desactivado", "Off"),
    "language": ("Idioma", "Language"),
    "languageSpanish": ("Español", "Spanish"),
    "languageEnglish": ("Inglés", "English"),
    "selectLanguage": ("Seleccionar idioma", "Select language"),
    "profileTitle": ("Perfil", "Profile"),
    "myPets": ("Mis mascotas", "My pets"),
    "myAppointments": ("Mis citas", "My appointments"),
    "notifications": ("Notificaciones", "Notifications"),
    "saved": ("Guardados", "Saved"),
    "favoritesLoadError": (
        "Error al cargar favoritos: {error}",
        "Error loading favorites: {error}",
    ),
    "noSavedClinicsTitle": (
        "No has guardado ninguna clínica",
        "You haven't saved any clinics",
    ),
    "noSavedClinicsSubtitle": (
        "Cuando guardes clínicas con el corazón, las verás aquí",
        "When you save clinics with the heart icon, they'll appear here",
    ),
    "findClinics": ("Encontrar clínicas", "Find clinics"),
    "personalData": ("Datos personales", "Personal details"),
    "emailAddress": ("Correo electrónico", "Email address"),
    "phonePrefix": ("Prefijo", "Prefix"),
    "phoneNumber": ("Número de teléfono", "Phone number"),
    "changePassword": ("Cambiar contraseña", "Change password"),
    "saveChanges": ("Guardar cambios", "Save changes"),
    "noChangesToSave": ("No hay cambios que guardar", "No changes to save"),
    "dataSaved": ("Datos guardados", "Data saved"),
    "saveError": ("Error al guardar: {error}", "Error saving: {error}"),
    "passwordMinLength": (
        "La contraseña debe tener al menos 6 caracteres",
        "Password must be at least 6 characters",
    ),
    "passwordsDoNotMatch": (
        "Las contraseñas no coinciden",
        "Passwords do not match",
    ),
    "passwordUpdated": ("Contraseña actualizada", "Password updated"),
    "newPassword": ("Nueva contraseña", "New password"),
    "confirmPassword": ("Confirmar contraseña", "Confirm password"),
    "updatePassword": ("Actualizar contraseña", "Update password"),
    "errorWithDetails": ("Error: {error}", "Error: {error}"),
    "navSearch": ("Buscar", "Search"),
    "navAppointments": ("Citas", "Appointments"),
    "navPets": ("Mascotas", "Pets"),
    "navProfile": ("Perfil", "Profile"),
    "navClinicHome": ("Inicio", "Home"),
    "navClinicAgenda": ("Agenda", "Schedule"),
    "navClinicPatients": ("Pacientes", "Patients"),
    "navMyClinic": ("Mi clínica", "My clinic"),
    "welcomeToVetNow": ("Bienvenido a VetNow", "Welcome to VetNow"),
    "welcomeToVetNowName": (
        "Bienvenido a VetNow, {name}!",
        "Welcome to VetNow, {name}!",
    ),
    "searchHintNameCityAddress": (
        "Buscar por nombre, ciudad o dirección",
        "Search by name, city, or address",
    ),
    "searchClinicsNearMe": (
        "Buscar clínicas cerca de mí",
        "Search clinics near me",
    ),
    "allSpecialties": ("Todas", "All"),
    "favoriteClinics": ("Clínicas favoritas", "Favorite clinics"),
    "noFavoriteClinicsTitle": (
        "Todavía no tienes clínicas favoritas",
        "You don't have favorite clinics yet",
    ),
    "noFavoriteClinicsSubtitle": (
        "Explora y pulsa el corazón en cualquier clínica para añadirla aquí.",
        "Browse and tap the heart on any clinic to add it here.",
    ),
    "upcomingAppointments": ("Próximas citas", "Upcoming appointments"),
    "noScheduledAppointmentsTitle": (
        "No tienes citas programadas",
        "You have no scheduled appointments",
    ),
    "noScheduledAppointmentsSubtitle": (
        "Reserva una cita y aparecerá aquí.",
        "Book an appointment and it will appear here.",
    ),
    "statusPending": ("Pendiente", "Pending"),
    "statusConfirmed": ("Confirmada", "Confirmed"),
    "locationDisabledTitle": ("Ubicación desactivada", "Location disabled"),
    "locationDisabledMessage": (
        "Activa el servicio de ubicación de tu dispositivo para ver las clínicas cercanas.",
        "Turn on location services on your device to see nearby clinics.",
    ),
    "locationPermissionTitle": (
        "Permiso de ubicación necesario",
        "Location permission required",
    ),
    "locationPermissionMessage": (
        "Para mostrarte las clínicas más cercanas necesitamos acceder a tu ubicación. "
        "Actívala en los ajustes de la app.",
        "To show you the nearest clinics we need access to your location. "
        "Enable it in the app settings.",
    ),
    "openSettings": ("Abrir ajustes", "Open settings"),
    "locationFetchError": (
        "No se pudo obtener tu ubicación: {error}",
        "Could not get your location: {error}",
    ),
    "searchClinicsTitle": ("Buscar clínicas", "Search clinics"),
    "searchHintShort": ("Nombre, ciudad o dirección", "Name, city, or address"),
    "searchTypeToSeeResults": (
        "Escribe para ver clínicas que coincidan",
        "Type to see matching clinics",
    ),
    "searchNoClinicsForQuery": (
        'No hay clínicas para "{query}"',
        'No clinics for "{query}"',
    ),
    "searchTryAnotherQuery": (
        "Prueba con otro nombre, ciudad o dirección",
        "Try another name, city, or address",
    ),
    "clinicNotFound": ("Clínica no encontrada", "Clinic not found"),
    "aboutUs": ("Sobre nosotros", "About us"),
    "specialties": ("Especialidades", "Specialties"),
    "clinicNoSpecialtiesConfigured": (
        "Esta clínica no tiene especialidades configuradas",
        "This clinic has no specialties configured",
    ),
    "bookAppointment": ("Reservar cita", "Book appointment"),
    "selectSpecialty": ("Selecciona especialidad", "Select specialty"),
    "nearbyClinicsTitle": ("Clínicas cercanas", "Nearby clinics"),
    "viewOnMap": ("Ver en el mapa", "View on map"),
    "noClinicsWithinRadius": (
        "No hay clínicas en {km} km",
        "No clinics within {km} km",
    ),
    "nearbyTryOtherSpecialty": (
        "Prueba con otra especialidad o amplía el radio de búsqueda.",
        "Try another specialty or widen the search radius.",
    ),
    "nearbyNeedsGps": (
        "Las clínicas necesitan tener su ubicación GPS registrada para aparecer aquí.",
        "Clinics need a registered GPS location to appear here.",
    ),
    "nearbyClinicsCount": (
        "{count, plural, =1{1 clínica cerca de ti} other{{count} clínicas cerca de ti}}",
        "{count, plural, =1{1 clinic near you} other{{count} clinics near you}}",
    ),
    "appointmentsTitle": ("Citas", "Appointments"),
    "petFilterLabel": ("Mascota", "Pet"),
    "allPets": ("Todas las mascotas", "All pets"),
    "petsLoadError": (
        "No se pudieron cargar mascotas",
        "Could not load pets",
    ),
    "tabScheduled": ("Programadas ({count})", "Scheduled ({count})"),
    "tabCompleted": ("Realizadas ({count})", "Completed ({count})"),
    "tabCancelled": ("Canceladas ({count})", "Cancelled ({count})"),
    "noCompletedAppointmentsTitle": (
        "No tienes citas realizadas",
        "You have no completed appointments",
    ),
    "completedAppointmentsSubtitle": (
        "Aquí verás el historial de tus visitas.",
        "Your visit history will appear here.",
    ),
    "noCancelledAppointmentsTitle": (
        "No tienes citas canceladas",
        "You have no cancelled appointments",
    ),
    "statusDone": ("Realizada", "Completed"),
    "statusCancelled": ("Cancelada", "Cancelled"),
    "cancelAppointment": ("Cancelar cita", "Cancel appointment"),
    "cancelAppointmentConfirm": (
        "¿Seguro que quieres cancelar esta cita?",
        "Are you sure you want to cancel this appointment?",
    ),
    "no": ("No", "No"),
    "yesCancel": ("Sí, cancelar", "Yes, cancel"),
    "deleteAppointment": ("Eliminar cita", "Delete appointment"),
    "deleteAppointmentConfirm": (
        "Se borrará esta cita de tu historial. No se puede deshacer.",
        "This appointment will be removed from your history. It cannot be undone.",
    ),
    "yesDelete": ("Sí, eliminar", "Yes, delete"),
    "delete": ("Eliminar", "Delete"),
    "deleteFailed": (
        "No se pudo eliminar: {error}",
        "Could not delete: {error}",
    ),
    "bookAppointmentTitle": ("Reservar cita", "Book appointment"),
    "bookingError": (
        "Error al reservar: {error}",
        "Booking error: {error}",
    ),
    "appointmentBookedTitle": ("¡Cita reservada!", "Appointment booked!"),
    "appointmentBookedBody": ("{date}", "{date}"),
    "viewMyAppointments": ("Ver mis citas", "View my appointments"),
    "clinicNoAppointmentsYetTitle": (
        "Esta clínica no acepta citas todavía",
        "This clinic does not accept appointments yet",
    ),
    "clinicNoSchedulesSubtitle": (
        "La clínica aún no ha configurado sus horarios de atención.",
        "The clinic has not set its opening hours yet.",
    ),
    "back": ("Volver", "Back"),
    "noSlotsThatDay": (
        "No hay horarios disponibles ese día",
        "No time slots available that day",
    ),
    "chooseAnotherDate": ("Elegir otra fecha", "Choose another date"),
    "selectTime": ("Selecciona una hora", "Select a time"),
    "bookingPetQuestion": (
        "¿Para qué mascota es la cita?",
        "Which pet is the appointment for?",
    ),
    "noPetsRegistered": (
        "No tienes mascotas registradas",
        "You have no registered pets",
    ),
    "addPet": ("Añadir mascota", "Add pet"),
    "appointmentSummary": ("Resumen de la cita", "Appointment summary"),
    "clinicLabel": ("Clínica", "Clinic"),
    "specialtyLabel": ("Especialidad", "Specialty"),
    "dateLabel": ("Fecha", "Date"),
    "timeLabel": ("Hora", "Time"),
    "petLabel": ("Mascota", "Pet"),
    "confirmBooking": ("Confirmar reserva", "Confirm booking"),
    "bookingContinueWithDate": (
        "Continuar con el {date}",
        "Continue with {date}",
    ),
    "weekdayLetters": ("D,L,M,X,J,V,S", "S,M,T,W,T,F,S"),
    "myPetsTitle": ("Mis mascotas", "My pets"),
    "noPetsYetTitle": (
        "Aún no has añadido mascotas",
        "You haven't added any pets yet",
    ),
    "noPetsYetSubtitle": (
        "Añade a tu mascota para gestionar sus citas",
        "Add your pet to manage their appointments",
    ),
    "uploadingPhoto": ("Subiendo foto…", "Uploading photo…"),
    "tapToAddPhoto": (
        "Toca para añadir o cambiar foto",
        "Tap to add or change photo",
    ),
    "takePhoto": ("Hacer foto", "Take photo"),
    "chooseFromGallery": ("Elegir de galería", "Choose from gallery"),
    "removeProfilePhoto": (
        "Quitar foto de perfil",
        "Remove profile photo",
    ),
    "editPetTooltip": ("Editar mascota", "Edit pet"),
    "deletePetTitle": ("Eliminar mascota", "Delete pet"),
    "deletePetConfirm": (
        "¿Seguro que quieres eliminar a {name}?",
        "Are you sure you want to delete {name}?",
    ),
    "newPet": ("Nueva mascota", "New pet"),
    "editPet": ("Editar mascota", "Edit pet"),
    "nameRequired": ("Nombre *", "Name *"),
    "nameRequiredError": (
        "El nombre es obligatorio",
        "Name is required",
    ),
    "species": ("Especie", "Species"),
    "breedOptional": ("Raza (opcional)", "Breed (optional)"),
    "birthDate": ("Fecha de nacimiento", "Date of birth"),
    "birthDateOptional": (
        "Fecha de nacimiento (opcional)",
        "Date of birth (optional)",
    ),
    "savePet": ("Guardar mascota", "Save pet"),
    "ageLessThanOneMonth": ("Menos de 1 mes", "Less than 1 month"),
    "ageMonths": (
        "{count, plural, =1{1 mes} other{{count} meses}}",
        "{count, plural, =1{1 month} other{{count} months}}",
    ),
    "ageOneYear": ("1 año", "1 year"),
    "ageYears": (
        "{count, plural, =1{1 año} other{{count} años}}",
        "{count, plural, =1{1 year} other{{count} years}}",
    ),
    "speciesDog": ("Perro", "Dog"),
    "speciesCat": ("Gato", "Cat"),
    "speciesRabbit": ("Conejo", "Rabbit"),
    "speciesHamster": ("Hámster", "Hamster"),
    "speciesBird": ("Ave", "Bird"),
    "speciesReptile": ("Reptil", "Reptile"),
    "speciesFish": ("Pez", "Fish"),
    "speciesOther": ("Otro", "Other"),
    "myClinicFallback": ("Mi clínica", "My clinic"),
    "today": ("Hoy", "Today"),
    "completeYourProfile": ("Completa tu perfil", "Complete your profile"),
    "completeProfileBannerBody": (
        "Los propietarios podrán encontrarte cuando completes los datos de tu clínica.",
        "Owners will be able to find you when you complete your clinic details.",
    ),
    "complete": ("Completar", "Complete"),
    "todayPatients": ("Pacientes de hoy", "Today's patients"),
    "pendingYourConfirmation": (
        "Pendiente de tu confirmación",
        "Awaiting your confirmation",
    ),
    "appointmentsAwaitingConfirmation": (
        "{count, plural, =1{1 cita esperando confirmación} other{{count} citas esperando confirmación}}",
        "{count, plural, =1{1 appointment awaiting confirmation} other{{count} appointments awaiting confirmation}}",
    ),
    "acceptOrRejectFromAgenda": (
        "Acepta o rechaza desde la agenda",
        "Accept or decline from the schedule",
    ),
    "activitySummary": ("Resumen de actividad", "Activity summary"),
    "quickAccess": ("Acceso rápido", "Quick access"),
    "manageYourAppointments": (
        "Gestiona tus citas",
        "Manage your appointments",
    ),
    "medicalRecords": ("Expedientes médicos", "Medical records"),
    "confirmedAppointmentsToday": (
        "citas confirmadas hoy",
        "confirmed appointments today",
    ),
    "noAppointmentsTodayEnjoy": (
        "Sin citas para hoy. Disfruta el día.",
        "No appointments today. Enjoy your day.",
    ),
    "nextAppointment": ("Próxima cita", "Next appointment"),
    "nextAppointments": ("Próximas citas", "Upcoming appointments"),
    "viewFullAgenda": ("Ver agenda completa", "View full schedule"),
    "appointmentsOverview": (
        "Vista general de tus citas",
        "Overview of your appointments",
    ),
    "viewAgenda": ("Ver agenda", "View schedule"),
    "scheduled": ("Programadas", "Scheduled"),
    "toConfirm": ("Por confirmar", "Pending confirmation"),
    "confirmedPatientsToday": (
        "{count, plural, =1{1 paciente confirmado hoy} other{{count} pacientes confirmados hoy}}",
        "{count, plural, =1{1 confirmed patient today} other{{count} confirmed patients today}}",
    ),
    "thisWeek": ("Esta semana", "This week"),
    "cancelledThisWeek": (
        "{count} canceladas esta semana",
        "{count} cancelled this week",
    ),
    "cancelledToday": ("{count} canceladas hoy", "{count} cancelled today"),
    "totalAwaitingConfirmation": (
        "{count} en total esperando tu confirmación",
        "{count} total awaiting your confirmation",
    ),
    "noConfirmedPatientsToday": (
        "Ningún paciente con cita confirmada para hoy.",
        "No patients with a confirmed appointment today.",
    ),
    "agendaTitle": ("Agenda", "Schedule"),
    "clinicProfileNotFound": (
        "No se encontró el perfil de clínica.",
        "Clinic profile not found.",
    ),
    "dateFilter": ("Fecha", "Date"),
    "tomorrow": ("Mañana", "Tomorrow"),
    "allAppointments": ("Todas las citas", "All appointments"),
    "tabPending": ("Pendientes ({count})", "Pending ({count})"),
    "tabConfirmedCount": ("Confirmadas ({count})", "Confirmed ({count})"),
    "noPendingAppointments": (
        "No hay citas pendientes",
        "No pending appointments",
    ),
    "newBookingsAppearHere": (
        "Las nuevas reservas aparecerán aquí.",
        "New bookings will appear here.",
    ),
    "noConfirmedAppointments": (
        "No hay citas confirmadas",
        "No confirmed appointments",
    ),
    "noCompletedAppointmentsClinic": (
        "No hay citas realizadas",
        "No completed appointments",
    ),
    "noCancelledAppointmentsClinic": (
        "No hay citas canceladas",
        "No cancelled appointments",
    ),
    "confirmAppointment": ("Confirmar cita", "Confirm appointment"),
    "confirmAppointmentBody": (
        "¿Confirmas esta cita? El propietario verá el estado actualizado.",
        "Confirm this appointment? The owner will see the updated status.",
    ),
    "yesConfirm": ("Sí, confirmar", "Yes, confirm"),
    "confirm": ("Confirmar", "Confirm"),
    "denyAppointment": ("Denegar cita", "Decline appointment"),
    "denyAppointmentBody": (
        "La cita quedará cancelada y el propietario verá el cambio.",
        "The appointment will be cancelled and the owner will see the change.",
    ),
    "yesDeny": ("Sí, denegar", "Yes, decline"),
    "deny": ("Denegar", "Decline"),
    "markAsDoneTitle": ("Marcar como realizada", "Mark as completed"),
    "markAsDoneBody": (
        "¿Marcar esta cita como realizada?",
        "Mark this appointment as completed?",
    ),
    "yesMark": ("Sí, marcar", "Yes, mark"),
    "markAsDone": ("Marcar como realizada", "Mark as completed"),
    "deleteAppointmentClinicBody": (
        "Se borrará esta cita del historial. No se puede deshacer.",
        "This appointment will be removed from history. It cannot be undone.",
    ),
    "patientsTitle": ("Pacientes", "Patients"),
    "patientsLoadError": (
        "No se pudieron cargar los pacientes.",
        "Could not load patients.",
    ),
    "noPatientsYetTitle": ("Sin pacientes aún", "No patients yet"),
    "noPatientsYetSubtitle": (
        "Los propietarios que reserven citas aparecerán aquí.",
        "Owners who book appointments will appear here.",
    ),
    "searchPatientByName": (
        "Buscar paciente por nombre",
        "Search patient by name",
    ),
    "noResultsForQuery": (
        'Sin resultados para "{query}"',
        'No results for "{query}"',
    ),
    "tryAnotherName": ("Prueba con otro nombre.", "Try another name."),
    "lastAppointment": ("Última cita · {date}", "Last appointment · {date}"),
    "petsTitle": ("Mascotas", "Pets"),
    "petsLoadErrorClinic": (
        "No se pudieron cargar las mascotas.",
        "Could not load pets.",
    ),
    "noPetsRegisteredClinic": (
        "Sin mascotas registradas",
        "No registered pets",
    ),
    "ownerNoPetsWithVisits": (
        "Este propietario no tiene mascotas con visitas.",
        "This owner has no pets with visits.",
    ),
    "history": ("Historial", "History"),
    "clinicLoadError": (
        "Error al cargar la clínica.",
        "Error loading clinic.",
    ),
    "clinicNotFoundShort": (
        "No se encontró la clínica.",
        "Clinic not found.",
    ),
    "historyLoadError": (
        "No se pudo cargar el historial.",
        "Could not load history.",
    ),
    "noVisitsWithPetTitle": (
        "Sin citas con esta mascota",
        "No appointments with this pet",
    ),
    "noVisitsWithPetSubtitle": (
        "Las citas pendientes, confirmadas o realizadas aparecerán aquí para añadir notas.",
        "Pending, confirmed, or completed appointments will appear here to add notes.",
    ),
    "clinicalNotes": ("Notas clínicas", "Clinical notes"),
    "clinicalNotesCount": (
        "Notas clínicas ({count})",
        "Clinical notes ({count})",
    ),
    "addAnotherNote": ("Añadir otra nota", "Add another note"),
    "addClinicalNote": ("Añadir nota clínica", "Add clinical note"),
    "confirmAppointmentToAddNotes": (
        "Confirma la cita en la agenda para poder añadir notas.",
        "Confirm the appointment in the schedule to add notes.",
    ),
    "deleteNoteTitle": ("Eliminar nota", "Delete note"),
    "deleteNoteConfirm": (
        "¿Seguro que quieres eliminar esta nota clínica? No se puede deshacer.",
        "Are you sure you want to delete this clinical note? It cannot be undone.",
    ),
    "editedOn": ("Editado {date}", "Edited {date}"),
    "edit": ("Editar", "Edit"),
    "newNote": ("Nueva nota", "New note"),
    "editNote": ("Editar nota", "Edit note"),
    "newNoteHint": (
        "Puedes añadir varias notas por visita.",
        "You can add several notes per visit.",
    ),
    "editNoteHint": (
        "Actualiza el texto de esta nota.",
        "Update the text of this note.",
    ),
    "noteHintExample": (
        "Ej. Revisión general, vacuna antirrábica aplicada…",
        "e.g. General check-up, rabies vaccine given…",
    ),
    "saveNote": ("Guardar nota", "Save note"),
    "retry": ("Reintentar", "Retry"),
    "newborn": ("recién nacido", "newborn"),
    "ageOneMonth": ("1 mes", "1 month"),
    "myClinicTitle": ("Mi clínica", "My clinic"),
    "unsavedChangesTitle": ("Cambios sin guardar", "Unsaved changes"),
    "unsavedChangesBody": (
        "Has modificado el perfil o los horarios de la clínica sin guardar. "
        "¿Qué deseas hacer?",
        "You changed the clinic profile or hours without saving. What do you want to do?",
    ),
    "save": ("Guardar", "Save"),
    "discardChanges": ("Descartar cambios", "Discard changes"),
    "saveTooltip": ("Guardar", "Save"),
    "schedulesLoadError": (
        "Error al cargar horarios: {error}",
        "Error loading hours: {error}",
    ),
    "locationRegisteredSnack": (
        "Ubicación registrada. Tu clínica ya aparecerá en búsquedas cercanas.",
        "Location saved. Your clinic will now appear in nearby searches.",
    ),
    "profileUpdated": ("Perfil actualizado", "Profile updated"),
    "profileSavedNoLocation": (
        'Perfil guardado, pero no se pudo obtener la ubicación. '
        'Revisa dirección y ciudad (ej. "Valdemoro") y vuelve a guardar.',
        'Profile saved, but location could not be obtained. '
        'Check address and city (e.g. "Valdemoro") and save again.',
    ),
    "registeringLocation": (
        "Registrando tu ubicación en el mapa…",
        "Registering your location on the map…",
    ),
    "locationBannerNeedsSave": (
        "Tu clínica aún no tiene coordenadas GPS. Completa dirección y ciudad, "
        "luego pulsa Guardar para aparecer en búsquedas cercanas.",
        "Your clinic has no GPS coordinates yet. Fill in address and city, "
        "then tap Save to appear in nearby searches.",
    ),
    "locationBannerEnterCity": (
        "Indica la ciudad (ej. Valdemoro) y la dirección para que los propietarios "
        "puedan encontrarte.",
        "Enter the city (e.g. Valdemoro) and address so owners can find you nearby.",
    ),
    "basicInformation": ("Información básica", "Basic information"),
    "clinicName": ("Nombre de la clínica", "Clinic name"),
    "address": ("Dirección", "Address"),
    "city": ("Ciudad", "City"),
    "phone": ("Teléfono", "Phone"),
    "contactEmail": ("Email de contacto", "Contact email"),
    "description": ("Descripción", "Description"),
    "requiredField": ("Campo obligatorio", "Required field"),
    "loadingSpecialties": (
        "Cargando especialidades…",
        "Loading specialties…",
    ),
    "appointmentDurationTitle": (
        "Duración de las citas",
        "Appointment duration",
    ),
    "appointmentDurationHelp": (
        "Cada franja reservable tendrá esta duración. Los propietarios verán "
        "los horarios disponibles ajustados al guardar.",
        "Each bookable slot will use this duration. Owners will see available "
        "times adjusted when you save.",
    ),
    "durationPerAppointment": (
        "Duración por cita",
        "Duration per appointment",
    ),
    "weeklyHours": ("Horarios semanales", "Weekly schedule"),
    "closed": ("Cerrado", "Closed"),
    "dayMonday": ("Lunes", "Monday"),
    "dayTuesday": ("Martes", "Tuesday"),
    "dayWednesday": ("Miércoles", "Wednesday"),
    "dayThursday": ("Jueves", "Thursday"),
    "dayFriday": ("Viernes", "Friday"),
    "daySaturday": ("Sábado", "Saturday"),
    "daySunday": ("Domingo", "Sunday"),
    "durationMinutes": ("{minutes} minutos", "{minutes} minutes"),
    "durationOneHour": ("1 hora", "1 hour"),
    "durationOneHourThirty": ("1 hora 30 min", "1 hour 30 min"),
    "durationTwoHours": ("2 horas", "2 hours"),
    "durationHours": ("{hours} horas", "{hours} hours"),
    "durationHoursMinutes": (
        "{hours} h {minutes} min",
        "{hours} h {minutes} min",
    ),
    "privacyPolicyTitle": ("Política de privacidad", "Privacy policy"),
    "termsOfServiceTitle": ("Términos y condiciones", "Terms and conditions"),
}
